apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o kuberes
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -o kuberes
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/rasa-network: "true"
        io.kompose.service: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: ""
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config-volume
        - mountPath: /etc/letsencrypt/live/rasabot.life
          name: nginx-cert-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - configMap:
          name: nginx-config
        name: nginx-config-volume
      - configMap:
          name: nginx-cert-config
        name: nginx-cert-volume
status: {}
