apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o kuberes
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: duckling
  name: duckling
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: duckling
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -o kuberes
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/rasa-network: "true"
        io.kompose.service: duckling
    spec:
      containers:
      - image: rasa/duckling:latest
        imagePullPolicy: ""
        name: duckling
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
